load_text = "Free Access to InterviewQues/ResumeAssistance/Material"
username = "//input[@id = 'username']"
password = "//input[@id = 'password']"
admin_usertype = "//input[@value ='admin']/following-sibling::span"
user_usertype = "//input[@value ='user']/following-sibling::span"
modal_body = "//div[@class = 'modal-body']"
cancel_btn = "id=cancelBtn"
okay_btn = "id=okayBtn"
role_select = "//select"
role_value = {"Student":"stud", "Teacher":"teach" , "Consultant":"consult"}
terms = "//input[@id = 'terms']"
sign_in = "//input[@id = 'signInBtn']"
warning_pop = "//div[contains(@class,'alert')]"
warning_text_incorrect = "//strong[text() = 'Incorrect']"
warning_text_empty = "//strong[text() = 'Empty']"