content_names = "//div[@id='leftmenuinnerinner']/a"
html_formatting = "//a[text() = 'HTML Formatting']"
content_after_html_formatting = "//a[text() = 'HTML Formatting']/following-sibling::a"
html_css = "//a[text()='HTML CSS']"
content_after_html_css = "//a[text()='HTML CSS']/following-sibling::a"
parent_active = "//a[@class = 'active']/parent::*"
html_iframe = "//a[text() = 'HTML Iframes']"
iframe_w3school = "//iframe[contains(@title,'W3Schools')]"
last_content = "//div[@id='leftmenuinnerinner']/a[last()]"