page_grid = "css=div.page-grid"
search_field = "//input[@aria-label = 'Search for anything']"
search_btn = "//input[@value = 'Search']"
buy_it_now = "//span[text()='Buy It Now' and contains(@class,'srp')]"
condition_list = "//span[text()='Condition']/ancestor::button"
openbox_condition = "//span[text()='Open box']/span[@class='checkbox']"
search_results = "//ul[contains(@class,'srp-results')]"
all_items = "//li[contains(@id,'item')]"
first_item_link = "(//li[contains(@id,'item')])[1]/descendant::div[@class = 's-item__title']"
advanced_search = "//a[@title='Advanced Search']"
