first_name = "css=input#firstName"
last_name = "css=input#lastName"
address = "css=input#addressLine1"
city = "css=input#city"
state = "css=input#stateOrProvince"
zip = "css=input#postalCode"
email = "css=input#email"
confirm_email = "css=input#emailConfirm"
phone = "css=input#phoneNumber"
done_btn = "//button[text() = 'Done']"