nav_bar_brand_up = "//a[@class = 'navbar-brand' and text()='ProtoCommerce']"
nav_link_home = "//a[@class = 'nav-link' and text()='Home']"
nav_link_shop = "//a[@class = 'nav-link' and text()='Shop']"
nav_bar_brand_down = "//a[@class = 'navbar-brand' and text()='ProtoCommerce Home']"
check_out = "//a[contains(text(),'Checkout')]"
shop_name = "//h1[text() = 'Shop Name']"
list_group_items = ["//a[text() = 'Category 1']","//a[text() = 'Category 2']","//a[text() = 'Category 3']"]
carousel = "id=carouselExampleIndicators"
iphone_x_label = "//a[text()='iphone X']"
iphone_x_add = "//a[text()='iphone X']/ancestor::div[@class='card-body']/following-sibling::*/button[contains(text(),'Add')]"
note_8_label = "//a[text()='Samsung Note 8']"
note_8_add = "//a[text()='Samsung Note 8']/ancestor::div[@class='card-body']/following-sibling::*/button[contains(text(),'Add')]"
nokia_edge_label = "//a[text()='Nokia Edge']"
nokia_edge_add = "//a[text()='Nokia Edge']/ancestor::div[@class='card-body']/following-sibling::*/button[contains(text(),'Add')]"
blackberry_label = "//a[text()='Blackberry']"
blackberry_add = "//a[text()='Blackberry']/ancestor::div[@class='card-body']/following-sibling::*/button[contains(text(),'Add')]"